services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    restart: always
    depends_on:
      - db
volumes:
  pg_data:
